from __future__ import annotations

import csv
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _typeshed import SupportsWrite

# go package name
PKG = "iso"

# https://github.com/datasets/country-codes/blob/main/data/country-codes.csv
COUNTRIES = "countries.csv"
COUNTRIES_OUT = "countries.go"

# https://github.com/datasets/currency-codes/blob/main/data/codes-all.csv
CURRENCIES = "currencies.csv"
CURRENCIES_OUT = "currencies.go"

# https://github.com/datasets/language-codes/blob/main/data/language-codes-3b2.csv
LANGUAGES = "languages.csv"
LANGUAGES_OUT = "languages.go"


PREAMBLE = "// Code generated by gen.py from csv; DO NOT EDIT."


def make_p(f: SupportsWrite[str]):
    def p(*s: object):
        print(*s, file=f)

    return p


def read_csv(name: str) -> list[dict[str, str]]:
    data: list[dict[str, str]] = []

    with open(name, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        header = next(reader)


        for row in reader:
            row = dict(zip(header, row))

            data.append(row)

    return data


def gen_countries():
    data = read_csv(COUNTRIES)

    with open(COUNTRIES_OUT, "w") as f:
        p = make_p(f)

        p(PREAMBLE)
        p(f"package {PKG}")
        p()
        p("var CountryAlpha2 = map[string]struct{}{")
        for row in data:
            alpha2 = row["ISO3166-1-Alpha-2"].lower()
            p(f'\t"{alpha2}": {{}},')
        p("}")
        p()
        p("var CountryAlpha3 = map[string]struct{}{")
        for row in data:
            alpha3 = row["ISO3166-1-Alpha-3"].lower()
            p(f'\t"{alpha3}": {{}},')
        p("}")


def gen_currencies():
    data = read_csv(CURRENCIES)

    with open(CURRENCIES_OUT, "w") as f:
        p = make_p(f)

        visited: set[str] = set()

        p(PREAMBLE)
        p(f"package {PKG}")
        p()
        p("var CurrencyAlpha = map[string]struct{}{")
        for row in data:
            code = row["AlphabeticCode"].lower()

            if code not in visited and code != "":
                p(f'\t"{code}": {{}},')
                visited.add(code)
        p("}")


def gen_languages():
    data = read_csv(LANGUAGES)

    with open(LANGUAGES_OUT, "w") as f:
        p = make_p(f)

        p(PREAMBLE)
        p(f"package {PKG}")
        p()
        p("var LanguageAlpha2 = map[string]struct{}{")
        for row in data:
            alpha2 = row["alpha2"].lower()
            p(f'\t"{alpha2}": {{}},')
        p("}")
        p()
        p("var LanguageAlpha3 = map[string]struct{}{")
        for row in data:
            alpha3 = row["alpha3-b"].lower()
            p(f'\t"{alpha3}": {{}},')
        p("}")


def main():
    gen_countries()
    gen_currencies()
    gen_languages()


if __name__ == "__main__":
    main()
