// Code generated by schemagen; DO NOT EDIT.

package main

// Ensure that [ABasicNested] type was not changed
func _() {
	type locked map[string]map[string][]string
	var v ABasicNested
	// Compiler error signifies that the type definition have changed.
	// Re-run the schemagen command to regenerate this file.
	_ = locked(v)
}

// Validate implements [validate.Validateable]
func (x ABasicNested) Validate() error {
	return nil
}
