// Code generated by schemagen; DO NOT EDIT.

package main

import (
	"fmt"
	validate "github.com/metafates/schema/validate"
)

// Ensure types are not changed
func _() {
	type locked map[string]MyStruct
	var v AMap
	// Compiler error signifies that the type definition have changed.
	// Re-run the schemagen command to regenerate this file.
	_ = locked(v)
}

// Validate implementes [validate.Validateable]
func (x AMap) Validate() error {
	for k0 := range x {
		{
			v0 := x[k0]
			err0 := validate.Validate(&v0)
			x[k0] = v0
			if err0 != nil {
				return validate.ValidationError{Inner: err0}.WithPath(fmt.Sprintf("[%v]", k0))
			}
		}
	}
	return nil
}
