// Code generated by schemagen; DO NOT EDIT.

package main

import (
	"fmt"
	validate "github.com/metafates/schema/validate"
)

// Ensure that [ASlice] type was not changed
func _() {
	type locked []MyStruct
	var v ASlice
	// Compiler error signifies that the type definition have changed.
	// Re-run the schemagen command to regenerate this file.
	_ = locked(v)
}

// Validate implements [validate.Validateable]
func (x ASlice) Validate() error {
	for i0 := range x {
		{
			err0 := validate.Validate(&x[i0])
			if err0 != nil {
				return validate.ValidationError{Inner: err0}.WithPath(fmt.Sprintf("[%v]", i0))
			}
		}
	}
	return nil
}
