// Code generated by schemagen; DO NOT EDIT.

package main

// Ensure types are not changed
func _() {
	type locked string
	var v Basic
	// Compiler error signifies that the type definition have changed.
	// Re-run the schemagen command to regenerate this file.
	_ = locked(v)
}

// Validate implementes [validate.Validateable]
func (x *Basic) Validate() error {
	return nil
}
