package main

import (
	"flag"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

type Env struct {
	File string
}

func NewEnv() Env {
	return Env{
		File: os.Getenv("GOFILE"),
	}
}

// Output returns output path for the generated file
func (e Env) Output() string {
	dir := filepath.Dir(e.File)
	ext := filepath.Ext(e.File)
	stem := strings.TrimSuffix(filepath.Base(e.File), ext)

	return filepath.Join(dir, stem+".schema"+ext)
}

func main() {
	// var validate bool
	var names []string

	// flag.BoolVar(&validate, "validate", false, "generate validate method")
	flag.BoolFunc("type", "", func(s string) error { names = append(names, s); return nil })

	flag.Parse()

	env := NewEnv()

	path := "."

	pkgs, err := packages.Load(
		&packages.Config{
			Mode: packages.LoadAllSyntax,
		},
		path,
	)
	if err != nil {
		log.Fatalln(err)
	}

	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	pkg := pkgs[0]

	scope := pkg.Types.Scope()

	f := jen.NewFilePathName(pkg.PkgPath, pkg.Name)
	f.HeaderComment("Code generated by schemagen. DO NOT EDIT.")

	for _, name := range names {
		obj := scope.Lookup(name)
		if obj == nil {
			log.Fatalf("unknown type: %s\n", name)
		}

		err = handleObject(f, obj.Type().(*types.Named))
		if err != nil {
			log.Fatalln(err)
		}
	}

	err = f.Save(env.Output())
	if err != nil {
		log.Fatalln(err)
	}
}

func handleObject(f *jen.File, named *types.Named) error {
	return genValidate(f, named)
}
